services:
  spark:
    image: spark:3.1
    container_name: spark
    networks:
      - coc-net

    volumes:
      - ../spark-conf:/opt/spark/conf
      - ../data:/data
      - ../model/ml:/models
      - ../data-exchange:/data-exchange
      - ../dags/jobs:/workspace/jobs
      - ../dags:/opt/airflow/dags

    ports:
      - "7077:7077"   # Spark master RPC
      - "8080:8080"   # Spark master UI
      - "4040:4040"   # Spark app UI (driver)

    environment:
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password

    command: >
      bash -lc "
        /opt/spark/sbin/start-master.sh --host spark --port 7077 &&
        /opt/spark/sbin/start-worker.sh spark://spark:7077 &&
        tail -f /opt/spark/logs/*
      "

networks:
  coc-net:
    external: true
