services:
  spark:
    image: spark:3.1
    container_name: spark
    networks:
      coc-net:
    volumes:
      - ../notebooks:/workspace
      - ../spark-conf:/opt/spark/conf
      - ../data:/data
      - ../model/ml:/models
      - ../data-exchange:/data
    ports:
      - "4040:4040"
      - "8888:8888"
    environment:
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
    command: >
      jupyter lab
       --ip=0.0.0.0
       --port=8888
       --no-browser
       --allow-root

networks:
  coc-net:
    external: true